hosts:
- hostname: iron1
  resources:
    iron1:
      kind: llnl/zpool
      parameters:
        pool: iron1
      requires: null
    iron1/mgs:
      kind: llnl/lustre
      parameters:
        dataset: iron1/mgs
        mountpoint: /mnt/lustre/MGS
        type: mgs
      requires: iron1
      target_type: mgs
    iron1/mdt1:
      kind: llnl/lustre
      parameters:
        dataset: iron1/mdt1
        mountpoint: /mnt/lustre/lobster-MDT0000
        type: mdt
      requires: iron1
      target_type: mdt
  fence_agent: null
  fence_parameters: null
- hostname: iron2
  resources:
    iron2:
      kind: llnl/zpool
      parameters:
        pool: iron2
      requires: null
    iron2/mdt1:
      kind: llnl/lustre
      parameters:
        dataset: iron2/mdt1
        mountpoint: /mnt/lustre/lobster-MDT0001
        type: mdt
      requires: iron2
      target_type: mdt
  fence_agent: null
  fence_parameters: null
- hostname: iron3
  resources:
    iron3:
      kind: llnl/zpool
      parameters:
        pool: iron3
      requires: null
    iron3/ost1:
      kind: llnl/lustre
      parameters:
        dataset: iron3/ost1
        mountpoint: /mnt/lustre/lobster-OST0000
        type: ost
      requires: iron3
      target_type: ost
  fence_agent: null
  fence_parameters: null
- hostname: iron4
  resources:
    iron4:
      kind: llnl/zpool
      parameters:
        pool: iron4
      requires: null
    iron4/ost1:
      kind: llnl/lustre
      parameters:
        dataset: iron4/ost1
        mountpoint: /mnt/lustre/lobster-OST0001
        type: ost
      requires: iron4
      target_type: ost
  fence_agent: null
  fence_parameters: null
- hostname: iron5
  resources:
    iron5:
      kind: llnl/zpool
      parameters:
        pool: iron5
      requires: null
    iron5/ost1:
      kind: llnl/lustre
      parameters:
        dataset: iron5/ost1
        mountpoint: /mnt/lustre/lobster-OST0002
        type: ost
      requires: iron5
      target_type: ost
  fence_agent: null
  fence_parameters: null
- hostname: iron6
  resources:
    iron6:
      kind: llnl/zpool
      parameters:
        pool: iron6
      requires: null
    iron6/ost1:
      kind: llnl/lustre
      parameters:
        dataset: iron6/ost1
        mountpoint: /mnt/lustre/lobster-OST0003
        type: ost
      requires: iron6
      target_type: ost
  fence_agent: null
  fence_parameters: null
failover_pairs:
- - iron1
  - iron2
- - iron3
  - iron4
- - iron5
  - iron6
